'use server';

import { supabaseAdmin } from '@/lib/supabase-admin';
import { createServerClient, type CookieOptions } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { sendWelcomeEmail } from '@/lib/resend';

// TODO: SEGURIDAD CRÍTICA - MEJORA REALIZADA
// Aunque hemos movido la autenticación al lado del servidor (evitando exponer credenciales),
// el short_id sigue siendo la contraseña. Si el ID es público (en gafetes), esto sigue siendo riesgoso.
// Se recomienda implementar un PIN o contraseña adicional en el futuro.

export async function checkUsernameAvailability(username: string): Promise<{ available: boolean; error?: string }> {
  try {
    const cleanUsername = username.trim().toLowerCase();
    if (!cleanUsername || cleanUsername.length < 3) {
      return { available: false, error: "El nombre de usuario debe tener al menos 3 caracteres." };
    }

    if (!/^[a-zA-Z0-9_.-]+$/.test(cleanUsername)) {
      return { available: false, error: "El usuario solo puede contener letras, números, puntos, guiones y guiones bajos." };
    }

    const { data, error } = await supabaseAdmin
      .from('profiles')
      .select('id')
      .ilike('username', cleanUsername)
      .maybeSingle();

    if (error) {
      console.error("checkUsernameAvailability error:", error);
      return { available: false, error: "Error al consultar disponibilidad." };
    }

    if (data) {
      return { available: false, error: "Este nombre de usuario ya está registrado." };
    }

    return { available: true };
  } catch (err: any) {
    return { available: false, error: "Error de servidor al verificar usuario." };
  }
}

export async function registerUser(data: {
  firstName: string;
  lastName: string;
  degree: string;
  gender: string;
  email: string;
  phone: string;
  username: string;
  password: string;
  conferenceId?: string;
  customData?: Record<string, any>;
}) {
  let userId: string | null = null;

  try {
    const cleanUsername = data.username.trim().toLowerCase();
    const cleanEmail = data.email.trim().toLowerCase();

    // 0. Verify username availability
    const availCheck = await checkUsernameAvailability(cleanUsername);
    if (!availCheck.available) {
      return { success: false, error: availCheck.error || "Nombre de usuario no disponible." };
    }

    // 1. Create Auth User with chosen password
    const { data: userData, error: userError } = await supabaseAdmin.auth.admin.createUser({
      email: cleanEmail,
      password: data.password,
      email_confirm: true, // Auto-confirm email
      user_metadata: {
        first_name: data.firstName,
        last_name: data.lastName,
        username: cleanUsername,
        custom_data: data.customData
      }
    });

    if (userError) {
      console.error("User creation error:", userError.message);
      return { success: false, error: userError.message };
    }

    if (!userData.user) {
      return { success: false, error: "No se pudo crear el usuario (sin datos)." };
    }

    userId = userData.user.id;

    // 2. Insert Profile (including username and user_password)
    // The Short ID is generated by a database trigger (BEFORE INSERT)
    const { data: profile, error: profileError } = await supabaseAdmin
      .from('profiles')
      .insert({
        id: userId,
        first_name: data.firstName,
        last_name: data.lastName,
        degree: data.degree,
        gender: data.gender,
        phone: data.phone,
        email: cleanEmail,
        username: cleanUsername,
        user_password: data.password
      })
      .select('short_id')
      .single();

    if (profileError) {
      console.error("Profile insertion error:", profileError);
      // Emergency rollback: delete auth user
      await supabaseAdmin.auth.admin.deleteUser(userId);
      return { success: false, error: "Error al crear perfil: " + profileError.message };
    }

    const shortId = profile.short_id;

    // 3. Register Access to Conference (if provided)
    if (data.conferenceId) {
      const { error: accessError } = await supabaseAdmin
        .from('conference_access')
        .upsert({
          user_id: userId,
          conference_id: data.conferenceId,
          last_accessed_at: new Date().toISOString()
        }, { onConflict: 'user_id, conference_id' });

      if (accessError) {
        console.error("Error linking user to conference on registration:", accessError);
      }
    }

    // 4. Send welcome email using Resend
    try {
      const emailResult = await sendWelcomeEmail({
        email: cleanEmail,
        firstName: data.firstName,
        username: cleanUsername,
        shortId,
      });

      if (!emailResult.success) {
        console.warn("[Register] Welcome email warning:", emailResult.error);
      } else {
        console.log(`[Register] Welcome email sent successfully (ID: ${emailResult.data?.id})`);
      }
    } catch (emailErr) {
      console.error("[Register] Unexpected exception while triggering welcome email:", emailErr);
    }

    return { success: true, data: { short_id: shortId, username: cleanUsername } };

  } catch (err: any) {
    console.error("Register Exception:", err);
    
    // Cleanup if userId exists
    if (userId) {
      try {
        await supabaseAdmin.auth.admin.deleteUser(userId);
      } catch (cleanupErr) {
        console.error("Failed to cleanup user after exception:", cleanupErr);
      }
    }

    return { success: false, error: err.message || "Error desconocido al registrar" };
  }
}

/**
 * Initiates login using username or email with password.
 */
export async function loginWithCredentials(identifier: string, password: string) {
  try {
    const cleanId = identifier.trim().toLowerCase();

    // 1. Find profile by username OR email
    const { data: profile, error } = await supabaseAdmin
      .from('profiles')
      .select('id, email, username')
      .or(`username.ilike.${cleanId},email.ilike.${cleanId}`)
      .maybeSingle();

    if (error || !profile) {
      return { success: false, error: "Usuario o contraseña incorrectos" };
    }

    // 2. Authenticate on Server Side setting cookies
    const cookieStore = await cookies();

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return cookieStore.getAll();
          },
          setAll(cookiesToSet) {
            try {
              cookiesToSet.forEach(({ name, value, options }) =>
                cookieStore.set(name, value, options)
              );
            } catch (error) {
              // Server Component warning ignore
            }
          },
        },
      }
    );

    // Sign in using email and chosen password
    const { data: authData, error: signInError } = await supabase.auth.signInWithPassword({
      email: profile.email,
      password: password,
    });

    if (signInError) {
      console.error("Login Error:", signInError.message);
      return { success: false, error: "Usuario o contraseña incorrectos" };
    }

    if (!authData.session) {
      return { success: false, error: "No se pudo establecer la sesión" };
    }

    // Update stored user_password in profile for user's private view
    await supabaseAdmin
      .from('profiles')
      .update({ user_password: password })
      .eq('id', profile.id);

    console.log('[SERVER] Login successful with credentials');

    // 3. Revalidate paths
    const { revalidatePath } = await import('next/cache');
    revalidatePath('/profile', 'page');
    revalidatePath('/', 'page');

    return {
      success: true,
      sessionEstablished: true,
      userId: authData.user.id
    };

  } catch (err: any) {
    console.error("Login Exception:", err);
    return { success: false, error: "Error al procesar el inicio de sesión" };
  }
}

/**
 * Returns the current authenticated user's complete profile details for private viewing.
 */
export async function getCurrentUserProfile() {
  try {
    const cookieStore = await cookies();
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() { return cookieStore.getAll(); },
          setAll() {},
        },
      }
    );

    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) {
      return { success: false, error: 'No hay sesión activa' };
    }

    const { data: profile, error: profileError } = await supabaseAdmin
      .from('profiles')
      .select('id, short_id, username, first_name, last_name, degree, gender, email, phone, user_password, created_at')
      .eq('id', user.id)
      .maybeSingle();

    if (profileError || !profile) {
      return { success: false, error: 'Perfil no encontrado' };
    }

    return { success: true, profile };
  } catch (err: any) {
    console.error('getCurrentUserProfile exception:', err);
    return { success: false, error: 'Error al obtener datos del perfil' };
  }
}

/**
 * Resolves the email address associated with a short_id or username.
 */
export async function resolveEmailByShortId(shortId: string): Promise<{ success: boolean; email?: string; error?: string }> {
  try {
    const { data: profile, error } = await supabaseAdmin
      .from('profiles')
      .select('email')
      .eq('short_id', shortId)
      .single();

    if (error || !profile) {
      return { success: false, error: 'ID no encontrado' };
    }

    return { success: true, email: profile.email };
  } catch (err: any) {
    console.error('resolveEmailByShortId Exception:', err);
    return { success: false, error: 'Error al procesar solicitud' };
  }
}

export async function loginWithId(shortId: string) {
  return loginWithCredentials(shortId, shortId);
}

export async function checkEmailForRecovery(email: string) {
  try {
    const { data, error } = await supabaseAdmin
      .from('profiles')
      .select('email')
      .ilike('email', email)
      .single();

    if (error || !data) {
      return { success: false, error: "Correo no encontrado en nuestros registros" };
    }
    return { success: true };
  } catch (err: any) {
    return { success: false, error: "Error al verificar el correo" };
  }
}

export async function verifyRecoveredUser(email: string, phone: string) {
  try {
    const { data, error } = await supabaseAdmin
      .from('profiles')
      .select('short_id, username, phone')
      .ilike('email', email)
      .single();

    if (error || !data) {
      return { success: false, error: "Registro no encontrado" };
    }

    const dbPhone = (data.phone || '').replace(/\D/g, '');
    const inputPhone = phone.replace(/\D/g, '');

    if (dbPhone !== inputPhone) {
      return { success: false, error: "El número de celular no coincide con el correo proporcionado" };
    }

    return { success: true, short_id: data.short_id, username: data.username };

  } catch (err: any) {
    return { success: false, error: "Error al verificar datos" };
  }
}
